### ISSUE TITLE
[PE-D][Tester E] Edit person with student number 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-T14-1/tp#180]
No one has a student number of 1, although it states there exists one in the address book.

![Image 4-5-24 at 4.31 PM.jpg](https://raw.githubusercontent.com/sarjinius/ped/main/files/db3a2352-192c-4ba8-98e2-a7bddaa59a6a.jpg)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: sarjinius/ped#2

**Comment by marclamp** [comment]
The new student ID `s/A1234567X` is probably duplicated with an existing one. 
Student ID of 1 is not a valid Student ID, potentially wrong error thrown.

**Comment by jeremiahlzz** [comment]
STUDENT_ID is being fuzzy matched. Should be exact match.
