### ISSUE TITLE
[PE-D][Tester B] Edit command throws error when identifying by student ID

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-T14-1/tp#182]
The eedit command throws an error when I am editing by student ID, even though the edit instructions allow me to choose a student ID.

![erra3.png](https://raw.githubusercontent.com/Dexter-Wong/ped/main/files/3afa02e7-ed07-4a6d-8183-243581a76769.png)

![erra3.5.png](https://raw.githubusercontent.com/Dexter-Wong/ped/main/files/05a22e64-d7f2-4c87-b070-ed7056068fe4.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Dexter-Wong/ped#3

**Comment by marclamp** [comment]
Invalid input, should use `s:A1234567X`.
