### ISSUE TITLE
[PE-D][Tester D] Unhandled runtime exception when parsing time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-T14-1/tp#184]
When this input is entered for time argument in add command:

13-11

a runtime error is thrown and is not handled.

![Screenshot 2024-04-05 at 16.35.19.png](https://raw.githubusercontent.com/laney0808/ped/main/files/69952290-ad57-46ab-baa2-0678c1ffb4e3.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: laney0808/ped#3

**Comment by marclamp** [comment]
command that throws the error:

`add n/John Doe s/A1234567X h/@john.doe e/johnd@example.com l/https://github.com/johndoe/tp t/tutorial-1 t/high-ability c/mon: 8-10, 10-12 tue: 13-11`
