### ISSUE TITLE
[PE-D][Tester A] The find command did not react to anything when "find n/" is entered

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-T14-1/tp#197]
find n/

The above command did not react to anything when entered. Not sure if there is a valid command, but the command is not reacting to anything. There is no error message. 

![image.png](https://raw.githubusercontent.com/AndrewOng2066/ped/main/files/ccd1214b-0623-431d-a535-378775907ce9.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AndrewOng2066/ped#4

**Comment by fy17ohhh** [comment]
duplicate #181
