### ISSUE TITLE
[PE-D][Tester D] No error message when "tuesday" is in the wrong format

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-T14-1/tp#200]
When the following is entered for add command:

tuesday: 10-11

No error was thrown. But when the same happened to another days, for example, 
wednesday

an error is thrown.d

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: laney0808/ped#7

**Comment by marclamp** [comment]
No error is thrown for any day if not spelt in the 3-LETTER-Day format, no matter which order or how many days

**Comment by marclamp** [comment]
Might potentially be a documentation update, there is no easy way to do prefix checking.
